{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "task-manager.fullname" . }}-secrets
  labels:
    {{- include "task-manager.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  nextauth-secret: {{ .Values.secrets.nextauthSecret | b64enc | quote }}
  nextauth-url: {{ .Values.secrets.nextauthUrl | b64enc | quote }}
  auth-trust-host: {{ .Values.secrets.authTrustHost | b64enc | quote }}
{{- end }}
