replicaCount: 1

image:
  repository: ralf090102/task-manager-app
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: task-manager.local
      paths:
        - path: /
          pathType: Prefix

secrets:
  databaseUrl: ""
  nextauthSecret: ""
  nextauthUrl: "http://task-manager.local"
  authTrustHost: "true"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

scheduler:
  enabled: true
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  image:
    repository: ralf090102/scheduler-service
    pullPolicy: IfNotPresent
    tag: latest
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

notification:
  enabled: false
  image:
    repository: ralf090102/notification-service
    pullPolicy: IfNotPresent
    tag: latest
  smtp:
    host: ""
    port: "587"
    from: "noreply@taskmanager.local"
    user: ""
    password: ""
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

monitoring:
  enabled: true
  serviceMonitor:
    scrapeInterval: 15s
    labels:
      release: monitoring
