{{- if .Values.meilisearch.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "task-manager.fullname" . }}-meilisearch-headless
  labels:
    {{- include "task-manager.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 7700
      name: http
  selector:
    {{- include "task-manager.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: meilisearch
{{- end }}
