{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "task-manager.fullname" . }}-minio-secret
  labels:
    {{- include "task-manager.labels" . | nindent 4 }}
type: Opaque
data:
  accessKey: {{ .Values.minio.accessKey | b64enc | quote }}
  secretKey: {{ .Values.minio.secretKey | b64enc | quote }}
{{- end }}
